### PR TITLE
JBVFS-206 VirtualFileURLConnection#getContent() doesn't call a conten…

### PR DESCRIPTION
**Pull request by TomasHofman**
…t handler

...determined by connection's contentType

https://issues.jboss.org/browse/JBVFS-206
https://issues.jboss.org/browse/JBEAP-15028

### CODE REVIEW

**Comment by dmlloyd** [comment]
Note that the "test-compile" section is not necessary.

**Comment by TomasHofman** [comment]
I added the bridger, thanks!

BTW were we in fact running risk with this break in binary compatibility, since the class is package-private?

**Comment by TomasHofman** [comment]
To answer my own question, different module could still define the same package, so yes, nvm.

**Comment by dmlloyd** [comment]
Ah! I didn't realize it was package-private, sorry!  No we don't have to worry about compatibility and your original patch is actually better in this case.

Sorry for the confusion; I don't really have a good excuse. :)

**Comment by TomasHofman** [comment]
No problem - reverted to the original version :).

**Pull request merged**
